#!/usr/bin/python3

import sys
import psycopg2

# set up some globals

usage = "Usage: best [N]"
db = None


# process command-line args
argc = len(sys.argv)
if argc > 2:
	print(usage)

if argc != 1:
#make sure argument is not a word
	if sys.argv[1].isdigit() == False:
		print("Usage: best [N]")
		exit(1)

	#make sure argument is 1 or more;
	firstArg = int(sys.argv[1])
	if firstArg < 1:
		print("Usage: best [N]")
		exit(1)

query = """
select Movies.rating, Movies.title, Movies.start_year
from Movies 
order by rating desc, title asc
limit %s
"""



# manipulate database

try:
	db = psycopg2.connect("dbname=imdb")
	cursor = db.cursor()
	if argc == 1:
		cursor.execute(query, [10])
	else:
		cursor.execute(query, [sys.argv[1]])

	for tuple in cursor.fetchall():
   		print("%s %s (%s)" % (tuple[0], tuple[1], tuple[2]))


except psycopg2.Error as err:
	print("DB error: ", err)
finally:
	if db:
		db.close()

